---

- name: setup application user
  include_tasks: setup_user.yml
  tags:
    - deploy

- name: setup gunicorn
  include_tasks: setup_gunicorn.yml
  tags:
    - deploy

- name: setup web application
  include_tasks: setup_app.yml
  tags:
    - deploy

- name: setup nginx config for working woth guincore
  include_tasks: setup_nginx.yml
  tags:
    - deploy
