---

- name: Download https://bootstrap.pypa.io/get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: "/home/{{ app_user }}/get-pip.py"
  become: true
  become_user: "{{ app_user }}"

- name: Iinstalling pip under web-app user
  shell:
    cmd: "python3 /home/{{ app_user }}/get-pip.py --user"
    creates: "/home/{{ app_user }}/.local/bin/pip3"
  become: true
  become_user: "{{ app_user }}"

- name: Remove get-pip.py
  file:
    path: "/home/{{ app_user }}/get-pip.py"
    state: absent

- pip:
    name: gunicorn
    extra_args: --user
    executable: "/home/{{ app_user }}/.local/bin/pip3"
  become: true
  become_user: "{{ app_user }}"

