---

- name: Ensure YUM is updated (only security)
  yum: name="*" state=latest security=yes

- name: Ensure pip3-python package is installed
  yum: name=python3 state=present

#- name: Ensure Development Tools are installed
#  yum: name="@Development tools" state=present

